/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActionsRouteImport } from './routes/actions'
import { Route as AirQualityRouteImport } from './routes/air-quality'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as MapRouteImport } from './routes/map'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TrendsRouteImport } from './routes/trends'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionsRoute = ActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => rootRouteImport,
} as any)
const AirQualityRoute = AirQualityRouteImport.update({
  id: '/air-quality',
  path: '/air-quality',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/air-quality': typeof AirQualityRoute
  '/analysis': typeof AnalysisRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/map': typeof MapRoute
  '/methodology': typeof MethodologyRoute
  '/settings': typeof SettingsRoute
  '/trends': typeof TrendsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/air-quality': typeof AirQualityRoute
  '/analysis': typeof AnalysisRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/map': typeof MapRoute
  '/methodology': typeof MethodologyRoute
  '/settings': typeof SettingsRoute
  '/trends': typeof TrendsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/air-quality': typeof AirQualityRoute
  '/analysis': typeof AnalysisRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/map': typeof MapRoute
  '/methodology': typeof MethodologyRoute
  '/settings': typeof SettingsRoute
  '/trends': typeof TrendsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actions'
    | '/air-quality'
    | '/analysis'
    | '/chat'
    | '/dashboard'
    | '/map'
    | '/methodology'
    | '/settings'
    | '/trends'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actions'
    | '/air-quality'
    | '/analysis'
    | '/chat'
    | '/dashboard'
    | '/map'
    | '/methodology'
    | '/settings'
    | '/trends'
  id:
    | '__root__'
    | '/'
    | '/actions'
    | '/air-quality'
    | '/analysis'
    | '/chat'
    | '/dashboard'
    | '/map'
    | '/methodology'
    | '/settings'
    | '/trends'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActionsRoute: typeof ActionsRoute
  AirQualityRoute: typeof AirQualityRoute
  AnalysisRoute: typeof AnalysisRoute
  ChatRoute: typeof ChatRoute
  DashboardRoute: typeof DashboardRoute
  MapRoute: typeof MapRoute
  MethodologyRoute: typeof MethodologyRoute
  SettingsRoute: typeof SettingsRoute
  TrendsRoute: typeof TrendsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actions': {
      id: '/actions'
      path: '/actions'
      fullPath: '/actions'
      preLoaderRoute: typeof ActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/air-quality': {
      id: '/air-quality'
      path: '/air-quality'
      fullPath: '/air-quality'
      preLoaderRoute: typeof AirQualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActionsRoute: ActionsRoute,
  AirQualityRoute: AirQualityRoute,
  AnalysisRoute: AnalysisRoute,
  ChatRoute: ChatRoute,
  DashboardRoute: DashboardRoute,
  MapRoute: MapRoute,
  MethodologyRoute: MethodologyRoute,
  SettingsRoute: SettingsRoute,
  TrendsRoute: TrendsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
